---
- name: Adding Target Accounts on PAM
  hosts: localhost
  gather_facts: false
  tasks:
    - name: create an Target Account on PAM
      uri:
        url: "https://wallix_host_name/api/targetgroups/{{ item[0].target_group }}"
        validate_certs: no
        force_basic_auth: yes
        status_code: 204
        user: "{{ pam_user }}"
        password: "{{ pam_password }}"
        method: PUT
        body_format: json
        body:
          session:
            accounts:
            - account: "{{ item[0].account }}"
              domain: "{{ var_domain_name }}"
              domain_type: global
              device: "{{ item[1].vm_name }}"
              service: RDP
              application: null
      with_nested: 
        - '{{ group_details }}'
        - '{{ vmdetails }}'
